[package]
name = "rust-summer"
version = "0.1.0"
authors = ["Peixian Wang <peixian@space.af>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
